### ISSUE TITLE
Launch preparations

### ISSUE THREAD

**Issue by geoffxy** [typeintandem/tandem#62]
- Investigative and preparatory work
  - [x] Investigate options for deployment (e.g. package both node/python3, one or the other, or neither) and pick an approach
  - [x] Relevant build scripts to package dependencies
  - [x] Manual smoke tests on common platforms (see which are currently supported)
    - [x] macOS (we expect it to work)
    - [ ] ~~Linux (we think it should work)~~
    - [ ] ~~Windows (we don't expect it to work)~~
    - [ ] ~~Cross platform testing (i.e. see if participants on different platforms can edit a document together)~~
    - [ ] ~~Make a decision on which platforms to support based on test outcome and any bugs that arise from testing~~
- Plugin release
  - [x] Create public repository for vim plugin
  - [x] Create public repository for neovim plugin
  - [x] Create public repository for sublime text plugin
  - [x] Write plugin release scripts that will commit to the public repositories
- Tandem website
  - [x] Register a domain
  - [x] Set up analytics
  - [x] Build an initial landing page
  - [x] Set up some kind of issue tracking system for public feedback (e.g. report a bug -> sends an email -> creates internal GitHub issue)
  - [x] Write the needed documentation to tell people about how to install and use Tandem
  - [x] Update website with download links, documentation, and feedback/bug reporting
  - [x] Create a video to showcase Tandem (? - Teletype has one)
- Tandem rendezvous server (dependent on outcome of #61)
  - [x] Set up AWS deployment of the rendezvous server
  - [x] Configure DNS appropriately if needed
  - [x] Add server side monitoring/analytics so we have visibility into its usage
- Tandem plugin rendezvous
  - [x] Display session uuid in a user friendly way
  - [x] Change "connect to" to accept a session uuid instead of host/port

**Comment by rageandqq** [comment]
@geoffxy think we're ready to close this one out? 🙏

**Comment by geoffxy** [comment]
We've already launched, so yeah I guess it's time to close this! 🎉
